directory: ~/media/music/
threaded: yes

plugins:
  - musicbrainz

import:
  run: yes
  write: yes
  copy: no
  move: yes
  autotag: yes
  languages: en

paths:
  default: $albumartist/$album/$track $title
